language: java

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

sudo: false

notifications:
  email:
    recipients:
      - temax359x@gmail.com
    on_success: never
    on_failure: always
